version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "127.0.0.1:82:80/tcp"
      - "127.0.0.1:444:443/tcp"
    environment:
      TZ: 'America/Chicago'
      DNS1: 172.28.1.3#5053
      DNS2: 172.28.1.3#5053
    volumes:
      - './etc-pihole/:/etc/pihole/' 
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    networks:
        dns_net:
            ipv4_address: 172.28.1.4 
  unbound:
    image: klutchell/unbound
    container_name: unbound
    volumes:
      - "./unbound/:/opt/unbound/etc/unbound/"
    restart: unless-stopped
    networks:
        dns_net:
            ipv4_address: 172.28.1.3
networks:
    dns_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
